---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: morbi-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
        - erikreider/SwayNotificationCenter
        - yalter/niri-git
        - tofik/nwg-shell 
      files: 
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://repo.librewolf.net/librewolf.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - wl-clipboard
        - distrobox
        - alsa-firmware
        - polkit
        - dbus-tools
        - dbus-daemon
        - qt5-wayland
        - qt6-wayland
        - wireplumber
        - pipewire
        - pulseaudio-utils
        - network-manager-applet
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome
        - NetworkManager-openconnect
        - NetworkManager-openconnect-gnome
        - bluez
        - bluez-tools
        - blueman
        - nautilus
        - gvfs-mtp
        - gvfs-gphoto2
        - gvfs-smb
        - gvfs-nfs
        - gvfs-fuse
        - gvfs-archive
        - heif-pixbuf-loader
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - pipewire-libs-extra
        - libfdk-aac
        - gstreamer1-plugins-bad
        - gstreamer1-plugins-ugly 
        - gnome-keyring
        - luajit
        - luajit-devel
        # specifically for testing in VMs, i.e GNOME-boxes
        - spice-server
        - spice-vdagent
        - spice-webdavd
        # all my personal stuff, niri, etc
        - mullvad
        - micro
        - starship
        - swww
        - swaync
        - niri
        - greetd
        - greetd-selinux
        - xwayland-satellite
        - adw-gtk3-theme
        - xdg-desktop-portal-gnome
        - firacode-nerd-fonts
        - fish
        - gtklock
        - wofi
        - fuzzel
        - eza
        - bat
        - cosmic-greeter
        - doas
        - tailscale
        - alacritty
        - librewolf
        - hyfetch
        - fastfetch
        - nwg-look
        # adb, fastboot, shit like that
        - android-tools 
    remove:
      packages:
        - cosmic-session
        - cosmic-term
        - cosmic-files
        - cosmic-settings
        - cosmic-screenshot
        - cosmic-workspaces
        - xdg-desktop-portal-cosmic
#  - type: files
#    files:
#      - source: system
#        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
#
#  - type: files
#    files:
#      - source: basics
#        destination: /

  - type: systemd
    system:
      enabled:
        - greetd.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

